import type { ContentRelationship } from "./model";

export const CONTENT_RELATIONSHIPS = [
  {
    fromEntryId: "pattern-hcd-engagement-intake-triage",
    toEntryId: "template-hcd-research-evidence-plan",
    type: "implements",
    label: "Decision-scoped research and evidence planning",
  },
  {
    fromEntryId: "template-hcd-research-evidence-plan",
    toEntryId: "method-evidence-first-synthesis",
    type: "related",
    label: "Traceable interpretation and synthesis",
  },
  {
    fromEntryId: "template-hcd-research-evidence-plan",
    toEntryId: "template-hcd-decision-evidence-record",
    type: "implements",
    label: "Evidence handoff to an accountable decision",
  },
  {
    fromEntryId: "framework-accessibility-governance-baseline",
    toEntryId: "template-hcd-research-evidence-plan",
    type: "implements",
    label: "Inclusive participation and evidence controls",
  },
  {
    fromEntryId: "framework-hcd-operating-model-baseline",
    toEntryId: "template-hcd-research-evidence-plan",
    type: "implements",
    label: "Evidence lifecycle planning artifact",
  },
  {
    fromEntryId: "landing-hcd-director-toolkit",
    toEntryId: "template-hcd-research-evidence-plan",
    type: "related",
    label: "Research and evidence planning template",
  },
  {
    fromEntryId: "framework-hcd-operating-model-baseline",
    toEntryId: "template-hcd-operating-agreement",
    type: "implements",
    label: "Minimum versioned operating agreement",
  },
  {
    fromEntryId: "template-hcd-operating-agreement",
    toEntryId: "pattern-hcd-engagement-intake-triage",
    type: "related",
    label: "Demand and prioritization operating pattern",
  },
  {
    fromEntryId: "template-hcd-operating-agreement",
    toEntryId: "pattern-hcd-delivery-checkpoints",
    type: "related",
    label: "Delivery integration operating pattern",
  },
  {
    fromEntryId: "template-hcd-operating-agreement",
    toEntryId: "framework-accessibility-governance-baseline",
    type: "related",
    label: "Accessibility governance controls",
  },
  {
    fromEntryId: "framework-hcd-operating-model-baseline",
    toEntryId: "framework-accessibility-governance-baseline",
    type: "implements",
    label: "Accessibility and responsible-practice governance",
  },
  {
    fromEntryId: "framework-accessibility-governance-baseline",
    toEntryId: "pattern-hcd-delivery-checkpoints",
    type: "implements",
    label: "Lifecycle delivery controls",
  },
  {
    fromEntryId: "framework-accessibility-governance-baseline",
    toEntryId: "tool-accessible-form-generator",
    type: "related",
    label: "Accessible component requirements tool",
  },
  {
    fromEntryId: "framework-accessibility-governance-baseline",
    toEntryId: "landing-design-system",
    type: "related",
    label: "Reusable accessible component foundation",
  },
  {
    fromEntryId: "framework-hcd-operating-model-baseline",
    toEntryId: "pattern-hcd-delivery-checkpoints",
    type: "implements",
    label: "Delivery integration operating pattern",
  },
  {
    fromEntryId: "pattern-hcd-delivery-checkpoints",
    toEntryId: "template-hcd-decision-evidence-record",
    type: "implements",
    label: "Checkpoint decision and exception record",
  },
  {
    fromEntryId: "pattern-hcd-delivery-checkpoints",
    toEntryId: "template-hcd-outcome-measurement-plan",
    type: "related",
    label: "Post-release measurement and learning",
  },
  {
    fromEntryId: "pattern-hcd-delivery-checkpoints",
    toEntryId: "tool-accessible-form-generator",
    type: "related",
    label: "Accessible implementation requirements tool",
  },
  {
    fromEntryId: "framework-hcd-operating-model-baseline",
    toEntryId: "template-hcd-outcome-measurement-plan",
    type: "implements",
    label: "Measures and learning artifact",
  },
  {
    fromEntryId: "template-hcd-decision-evidence-record",
    toEntryId: "template-hcd-outcome-measurement-plan",
    type: "related",
    label: "Decision follow-through and review evidence",
  },
  {
    fromEntryId: "template-hcd-outcome-measurement-plan",
    toEntryId: "case-study-navy-kpi-dashboard",
    type: "related",
    label: "Illustrative decision-support dashboard concept",
  },
  {
    fromEntryId: "method-evidence-first-synthesis",
    toEntryId: "template-hcd-decision-evidence-record",
    type: "implements",
    label: "Decision-level evidence and rationale record",
  },
  {
    fromEntryId: "pattern-hcd-engagement-intake-triage",
    toEntryId: "template-hcd-decision-evidence-record",
    type: "related",
    label: "Decision continuity after intake and routing",
  },
  {
    fromEntryId: "framework-hcd-operating-model-baseline",
    toEntryId: "template-hcd-decision-evidence-record",
    type: "implements",
    label: "Decision-rights and organizational-memory artifact",
  },
  {
    fromEntryId: "framework-hcd-operating-model-baseline",
    toEntryId: "pattern-hcd-engagement-intake-triage",
    type: "implements",
    label: "Demand and prioritization operating pattern",
  },
  {
    fromEntryId: "landing-hcd-director-toolkit",
    toEntryId: "pattern-hcd-engagement-intake-triage",
    type: "related",
    label: "HCD demand and routing pattern",
  },
  {
    fromEntryId: "landing-hcd-director-toolkit",
    toEntryId: "framework-hcd-operating-model-baseline",
    type: "related",
    label: "Director-level governance and operating model",
  },
  {
    fromEntryId: "framework-hcd-operating-model-baseline",
    toEntryId: "method-evidence-first-synthesis",
    type: "related",
    label: "Evidence lifecycle method",
  },
  {
    fromEntryId: "framework-hcd-operating-model-baseline",
    toEntryId: "case-study-navy-hr-automated-hcd",
    type: "demonstrates",
    label: "Operational-design example",
  },
  {
    fromEntryId: "landing-about",
    toEntryId: "landing-hcd-director-toolkit",
    type: "explains",
    label: "Public leadership toolkit and practice",
  },
  {
    fromEntryId: "landing-about",
    toEntryId: "guidance-ai-assisted-mykmhub-development",
    type: "explains",
    label: "MyKMHub development practice",
  },
  {
    fromEntryId: "landing-hcd-director-toolkit",
    toEntryId: "method-evidence-first-synthesis",
    type: "related",
    label: "Evidence and synthesis leadership method",
  },
  {
    fromEntryId: "landing-hcd-director-toolkit",
    toEntryId: "tool-accessible-form-generator",
    type: "related",
    label: "Accessible delivery requirements tool",
  },
  {
    fromEntryId: "landing-hcd-director-toolkit",
    toEntryId: "guidance-ai-assisted-mykmhub-development",
    type: "related",
    label: "Governed AI-assisted delivery practice",
  },
  {
    fromEntryId: "guidance-ai-assisted-mykmhub-development",
    toEntryId: "landing-design-system",
    type: "explains",
    label: "Design-system and accessibility implementation context",
  },
  {
    fromEntryId: "guidance-ai-assisted-mykmhub-development",
    toEntryId: "landing-tools",
    type: "related",
    label: "Working applications produced through this development practice",
  },
  {
    fromEntryId: "tool-ai-image-prompt-wizard",
    toEntryId: "case-study-ai-image-prompt-wizard",
    type: "implements",
    label: "Design context and original product concept",
  },
  {
    fromEntryId: "tool-accessible-form-generator",
    toEntryId: "case-study-accessible-form-generator",
    type: "implements",
    label: "Design context and outcomes",
  },
  {
    fromEntryId: "case-study-hcd-velocity-engine",
    toEntryId: "case-study-navy-hr-automated-hcd",
    type: "same-effort",
    label: "A broader operational-design perspective on the same effort",
  },
  {
    fromEntryId: "case-study-hcd-velocity-engine",
    toEntryId: "method-evidence-first-synthesis",
    type: "demonstrates",
    label: "Method used in this work",
  },
  {
    fromEntryId: "tool-evidence-traceability-matrix",
    toEntryId: "case-study-hcd-velocity-engine",
    type: "implements",
    label: "Related portfolio case study",
  },
] satisfies readonly ContentRelationship[];
